exports.myFirstProject = 
{  
  "connections":[  
    {  
      "kind":"addConnection",
      "startNodeId":398809118,
      "startPortIndex":0,
      "endNodeId":23624844,
      "endPortIndex":0,
      "_id":964734507,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":604762864,
      "startPortIndex":0,
      "endNodeId":398809118,
      "endPortIndex":0,
      "_id":647386019,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":598617458,
      "startPortIndex":0,
      "endNodeId":23624844,
      "endPortIndex":1,
      "_id":564971549,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":3271050,
      "startPortIndex":0,
      "endNodeId":598617458,
      "endPortIndex":2,
      "_id":742143501,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":440238000,
      "startPortIndex":0,
      "endNodeId":42665510,
      "endPortIndex":0,
      "_id":661808583,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":42665510,
      "startPortIndex":0,
      "endNodeId":945248858,
      "endPortIndex":0,
      "_id":359041827,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":604762864,
      "startPortIndex":0,
      "endNodeId":398809118,
      "endPortIndex":1,
      "_id":899758279,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "kind":"addConnection",
      "startNodeId":823934643,
      "startPortIndex":0,
      "endNodeId":42665510,
      "endPortIndex":1,
      "_id":764520692,
      "startProxy":false,
      "endProxy":false,
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxyPosition":[  
        0,
        0
      ],
      "hidden":false
    },
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":794491759,
      "endPortIndex":1,
      "endNodeId":440238000,
      "startPortIndex":0,
      "startNodeId":282252545,
      "kind":"addConnection"
    },
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":965267809,
      "endPortIndex":2,
      "endNodeId":440238000,
      "startPortIndex":0,
      "startNodeId":498266200,
      "kind":"addConnection"
    },
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":267211310,
      "endPortIndex":0,
      "endNodeId":317753978,
      "startPortIndex":0,
      "startNodeId":440238000,
      "kind":"addConnection"
    },
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":573083411,
      "endPortIndex":2,
      "endNodeId":42665510,
      "startPortIndex":0,
      "startNodeId":317753978,
      "kind":"addConnection"
    }
  ],
  "nodes":[  
    {  
      "name":"DefaultNodeName",
      "position":[  
        4596,
        4119
      ],
      "typeName":"SolidExtrusion",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        true,
        false
      ],
      "_id":23624844,
      "replication":"applyLongest",
      "extra":{  
        "script":"A;"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4350,
        4067
      ],
      "typeName":"RegularPolygon",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false,
        false,
        false
      ],
      "_id":398809118,
      "replication":"applyLongest",
      "extra":{  
        "script":"A;"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4062,
        4085
      ],
      "typeName":"Number",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  

      ],
      "_id":604762864,
      "replication":"applyLongest",
      "extra":{  
        "value":8,
        "min":0,
        "step":0.1,
        "max":20
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4351,
        4181
      ],
      "typeName":"Vector",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false,
        false,
        false
      ],
      "_id":598617458,
      "replication":"applyLongest",
      "extra":{  
        "script":"A;"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4063,
        4230
      ],
      "typeName":"Number",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  

      ],
      "_id":3271050,
      "replication":"applyLongest",
      "extra":{  
        "max":40,
        "step":0.1,
        "min":-40,
        "value":15
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4346,
        4449
      ],
      "typeName":"Range",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false,
        false,
        false
      ],
      "_id":440238000,
      "replication":"applyLongest",
      "extra":{  
        "script":"A;"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4859,
        4452
      ],
      "typeName":"Vector",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false,
        false,
        false
      ],
      "_id":42665510,
      "replication":"applyLongest",
      "extra":{  
        "script":"A;"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        5006,
        4451
      ],
      "typeName":"Point",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false
      ],
      "_id":945248858,
      "replication":"applyLongest",
      "extra":{  
        "script":"A;"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4047,
        4442
      ],
      "typeName":"Number",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  

      ],
      "_id":282252545,
      "replication":"applyLongest",
      "extra":{  
        "max":100,
        "step":0.1,
        "min":0,
        "value":20
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4534,
        4486
      ],
      "typeName":"Number",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  

      ],
      "_id":823934643,
      "replication":"applyLongest",
      "extra":{  
        "max":150,
        "step":0.1,
        "min":-150,
        "value":30
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4050,
        4532
      ],
      "typeName":"Number",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  

      ],
      "_id":498266200,
      "replication":"applyLongest",
      "extra":{  
        "max":150,
        "step":0.1,
        "min":0,
        "value":150
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4501,
        4561
      ],
      "typeName":"Script",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false
      ],
      "_id":317753978,
      "replication":"applyLongest",
      "extra":{  
        "script":"10 * Sin(A);"
      }
    }
  ],
  "name":"My First Project",
};

exports.myFirstCustomNode = 
{
  "connections":[  
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":137881318,
      "endPortIndex":0,
      "endNodeId":263728761,
      "startPortIndex":0,
      "startNodeId":253762878,
      "kind":"addConnection"
    },
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":525878839,
      "endPortIndex":1,
      "endNodeId":263728761,
      "startPortIndex":0,
      "startNodeId":253762878,
      "kind":"addConnection"
    },
    {  
      "hidden":false,
      "endProxyPosition":[  
        0,
        0
      ],
      "startProxyPosition":[  
        0,
        0
      ],
      "endProxy":false,
      "startProxy":false,
      "_id":144876797,
      "endPortIndex":0,
      "endNodeId":892555475,
      "startPortIndex":0,
      "startNodeId":263728761,
      "kind":"addConnection"
    }
  ],
  "nodes":[  
    {  
      "name":"DefaultNodeName",
      "position":[  
        4107,
        4161
      ],
      "typeName":"Input",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  

      ],
      "_id":253762878,
      "replication":"applyLongest",
      "extra":{  
        "name":"X"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4548,
        4156
      ],
      "typeName":"Output",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        true
      ],
      "_id":892555475,
      "replication":"applyLongest",
      "extra":{  
        "name":"X * X"
      }
    },
    {  
      "name":"DefaultNodeName",
      "position":[  
        4359,
        4152
      ],
      "typeName":"Multiply",
      "selected":false,
      "visible":true,
      "ignoreDefaults":[  
        false,
        false
      ],
      "_id":263728761,
      "replication":"applyLongest",
      "extra":{  

      }
    }
  ],
  "name":"My First Custom Node",
  "isCustomNode": true
};